### ISSUE TITLE
Practica Architech

### ISSUE THREAD

**Issue by Lissete7** [SistemasTecTlaxiaco/practica-architect-Lissete7#2]
[Practica Architech_Lizzete Leòn Gonzalez.pdf](https://github.com/SistemasTecTlaxiaco/practica-architect-Lissete7/files/7180693/Practica.Architech_Lizzete.Leon.Gonzalez.pdf)

**Comment by CxrlosMX** [comment]
Excelente trabajo. 
Calificación obtenida: 20 puntos

**Comment by josealfredo79** [comment]
Faltan los parametros por valor o por referencia...
